package prototipus;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cistern.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//

import java.io.IOException;

import javax.imageio.ImageIO;

public class Cistern extends Component implements Updateable {
	public Cistern() {
		pumpPlaceable = false;
		node = true;
		itemSource = true;
		broken = false;
		leaks = false;
		try {
			sprite = ImageIO.read(this.getClass().getResource("cistern.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public void repaired() {
	}
	
	public void malfunction() {
	}
	
	public void punctured() {
	}
	
	public void updateStatus() {
	}
	
	public String toString() {
		return "Cistern";
	}
}
