package prototipus;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cistern.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//

public class Cistern extends Component implements Updateable {
	public Cistern() {
		pumpPlaceable = false;
		node = true;
		itemSource = true;
		broken = false;
		leaks = false;
	}
	
	public void repaired() {
	}
	
	public void malfunction() {
	}
	
	public void punctured() {
	}
	
	public void update(){
	}
}
