package prototipus;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pipe.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//

public class Pipe extends Component {
	
	public Pipe(int capacity) {
		pumpPlaceable = true;
		node = false;
		itemSource = false;
		broken = false;
		leaks = false;
		this.capacity = capacity;
	}
	
	public Pipe() {
		pumpPlaceable = true;
		node = false;
		itemSource = false;
		broken = false;
		leaks = false;
		this.capacity = 10;
	}
	
	public void repaired() {
		setLeaks(false);
		resetPunctureCounter();
	}
	
	public void malfunction() {
	}
	
	public void punctured() {
		setLeaks(true);
	}
	
	public void updateStatus() {
		if (output != null && waterLevel > 0 && !leaks) {
			boolean isOutputFull = output.isFull();
			if (!isOutputFull) {
				output.waterFlows();
				this.takeWater();
			}
		}
		if (leaks && waterLevel > 0){
			leakedWater++;
			this.takeWater();
		}
		decreaseSlipperyCounter();
		decreaseStickyCounter();
		decreasePunctureCounter();
	}

	public void waterFlows() {
			addWater();
	}
	
	public void decreaseSlipperyCounter() {
		if(slipperyCounter > 0)
			slipperyCounter --;
	}
	
	public void decreaseStickyCounter() {
		if(stickyCounter > 0)
			stickyCounter --;
	}
	
	public void decreasePunctureCounter() {
		if(punctureCounter > 0)
			punctureCounter --;
	}
	
	public void setLeaks(boolean value) {
		leaks = value;
	}

	public boolean getLeaks()
	{
		return leaks;
	}
	public String toString() {
		return "Pipe";
	}

	public boolean isSticky()
	{
		return stickyCounter > 0;
	}

	public boolean isSlippery()
	{
		return slipperyCounter > 0;
	}
}
