package prototipus;


import java.util.ArrayList;
import java.util.List;
import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//




public abstract class Player {
	protected int stuckCounter;
	public final int stuckTime = 10;
	protected Component host;
	
	private void slips() {
		ArrayList<Component> neighboursOfHostPipe = host.getNeighbours();
		Random random = new Random();
		setNewHost(neighboursOfHostPipe.get(random.nextInt(0, 2)));
	}
	
	public void moveTo(Component dest) {
		if(stuckCounter > 0)
			return;
		boolean destCanBeSteppedOn = dest.canBeSteppedOn();
		int destStickyUntil = dest.getStickyCounter();
		int destSlipperyUntil = dest.getSlipperyCounter();
		
		if(destCanBeSteppedOn) {
			if(destSlipperyUntil > 0) {
				slips();
				return;
			}
			if(destStickyUntil > 0) {
				stuckCounter = stuckTime;
			}
			setNewHost(dest);
		}
	}
	
	public void changePumpInput(Component input) {
		if(host.getNode())
			host.setInput(input);
	}
	
	public void changePumpOutput(Component output) {
		if(host.getNode())
			host.setOutput(output);
	}
	
	public void sabotage() {
		host.punctured();
	}
	
	public void makeSticky() {
		boolean isHostNode = host.getNode();
		if(!isHostNode) {
			host.resetStickyCounter();
		}
	}
	
	public void setNewHost(Component dest) {
		host.removePlayer(this);
		dest.addPlayer(this);
		host = dest;
	}
	
	public void updateStatus() {
		decreaseStuckCounter();
	}
	
	public String toString() {
		return "stuckCounter: " + stuckCounter;
	}
	
	public Component getHost() {
		return host;
	}
	
	public void decreaseStuckCounter() {
		if(stuckCounter > 0)
			stuckCounter --;
	}
}
