package prototipus;

import java.util.Random;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pump.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//




public class Pump extends Component {
	private Random random = new Random();
	
	public Pump(int capacity) {
		pumpPlaceable = false;
		node = true;
		itemSource = false;
		broken = false;
		leaks = false;
		this.capacity = capacity;
	}
	
	public Pump() {
		pumpPlaceable = false;
		node = true;
		itemSource = false;
		broken = false;
		leaks = false;
		this.capacity = 10;
	}
	
	public void repaired() {
		broken = false;
	}
	
	public void malfunction() {
		broken = true;
	}
	
	public void punctured() {
	}

	public void update(){
		if(!broken){
			output.addWater();
			takeWater();
			int rand = random.nextInt(100);
			if(rand < 5){
				malfunction();
			}
		}
	}
	
	public void update() {
		if(random.nextInt(100) < 2) // 2% esely
			malfunction();
		if(!broken)
			waterFlows();
	}
}
