package prototipus;

import java.io.IOException;
import java.util.Random;

import javax.imageio.ImageIO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pump.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//




public class Pump extends Component {
	private Random random = new Random();
	
	public Pump(int capacity) {
		pumpPlaceable = false;
		node = true;
		itemSource = false;
		broken = false;
		leaks = false;
		this.capacity = capacity;
		try {
			sprite = ImageIO.read(getClass().getResource("pump.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public Pump() {
		pumpPlaceable = false;
		node = true;
		itemSource = false;
		broken = false;
		leaks = false;
		this.capacity = 10;
		try {
			sprite = ImageIO.read(getClass().getResource("pump.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public void repaired() {
		broken = false;
	}
	
	public void malfunction() {
		broken = true;
	}
	
	public void punctured() {
	}
	
	public void updateStatus() {
		if(random.nextInt(100) < 2) // 2% esely
			malfunction();
		if(!broken)
			waterFlows();
	}
}
