package prototipus;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Spring.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//




public class Spring extends Component implements Updateable{
	public Spring() {
		pumpPlaceable = false;
		node = true;
		itemSource = false;
		broken = false;
		leaks = false;
	}
	
	public void repaired() {
	}
	
	public void malfunction() {
	}

	public void update(){
		for (Component c : neighbours) {
			c.addWater();
			takeWater();
		}
	}
	
	public void punctured() {
	}
	
	/*public void updateStatus() {
		for(Component neighbour : neighbours) 
			neighbour.addWater();
	}*/
	
	public void update(){
		for (Component c : neighbours) {
			c.addWater();
			takeWater();
		}
	}
}
