package prototipus;

import java.io.IOException;

import javax.imageio.ImageIO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Spring.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//




public class Spring extends Component implements Updateable{
	public Spring() {
		pumpPlaceable = false;
		node = true;
		itemSource = false;
		broken = false;
		leaks = false;
		try {
			sprite = ImageIO.read(this.getClass().getResource("spring.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public void repaired() {
	}
	
	public void malfunction() {
	}
	
	public void punctured() {
	}
	
	public void updateStatus() {
		for(Component neighbour : neighbours) 
			neighbour.addWater();
	}
	
	public String toString() {
		return "Sring";
	}
}
