package prototipus;

import java.io.IOException;

import javax.imageio.ImageIO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Spring.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//

/**A játékbeli forrás megjelenítője, a vízfolyás folyamatának megkezdésére alkalmas.*/
public class Spring extends Component implements Updateable{
	/**Az osztály konstuktora.*/
	public Spring() {
		pumpPlaceable = false;
		node = true;
		itemSource = false;
		broken = false;
		leaks = false;
	}

	/**Üres függvény, nincs implementációja.*/
	public void repaired() {
	}

	/**Üres függvény, nincsen implementációja.*/
	public void malfunction() {
	}

	/**Üres függvény ninsen implementációja.*/
	public void punctured() {
	}

	/**Az összes szomszédjában való víz folyatására alkalmas függvény.*/
	public void updateStatus() {
		for(Component neighbour : neighbours)
			if(!neighbour.isFull())
				neighbour.waterFlows();
	}

	/**Üres függvény, nincsen implementációja.*/
	public void waterFlows() {

	}

	/**Az osztály szövegesítése.
	 * @return String*/
	public String toString() {
		return "Spring";
	}
}
