package prototipus;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Timer.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//




public class Timer {
	private ArrayList<Updateable> updateables;
	
	public void tick() {
		for(Updateable updateable:updateables)
			updateable.updateStatus();
	}
}
