package prototipus;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Updateable.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//




interface Updateable {
	void updateStatus();
}
