package prototipus;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Updateable.java
//  @ Date : 4/22/2023
//  @ Author : 
//
//



/**Léptethető objektumok közös interfésze. Minden léptethető osztálynak
 *implementálnia kell ezt az interfészt.*/
interface Updateable {
	/**Függvény felüldefiniálásra.*/
	void updateStatus();
}
